### ISSUE TITLE
Using with IOptions

### ISSUE THREAD

**Issue by kkharji** [MrDave1999/dotenv.core#146] opened 2023-07-20 09:43 UTC
Hello @MrDave1999 

I've followed the example package using `IOptions`, also multiple hacks and ways, but no matter I always get empty values in my classes. I'm on `DotEnv.Core 3.0.0`. 

Thanks

**Comment by kkharji** [comment] 2023-07-22 15:06
I have multi-package repo, where it implement clean architecture.

I've tried the sample, however, I could not get my values, for example, I have `connectionString` that always comes to have empty value

```cs
new EnvLoader().LoadEnv();
builder.Configuration.AddEnvironmentVariables();

builder.Services.Configure<ConfigData>(builder.Configuration);

```

After a while of testing and trying to make it work, I used Singleton which works
```cs

new EnvLoader().LoadEnv();
builder.Configuration.AddEnvironmentVariables();

var config = new EnvBinder().Bind<ConfigData>();
builder.Services.AddSingleton<ConfigData>(config);
```

**Comment by MrDave1999** [comment] 2023-07-22 15:32
@kkharji Ok, I'll do some tests and let you know.

**Comment by MrDave1999** [comment] 2023-07-23 21:03
Hello @kkharji,

I have tried to reproduce your problem but could not.

This code block is perfectly valid and works for me:
```cs
new EnvLoader().LoadEnv();
builder.Configuration.AddEnvironmentVariables();

builder.Services.Configure<ConfigData>(builder.Configuration);
```
`IOptions<ConfigData>` **is registered as a singleton by default** and I can access the configuration without problems from the controller.

That means that the error must be something else, check if the .env file is being loaded using the following option:
```cs
new EnvLoader()
    .EnableFileNotFoundException()
    .LoadEnv();
```

If it is not too much trouble, it would be a great help if you could create a sample repository where the error can be reproduced.

**Comment by MrDave1999** [comment] 2023-07-30 15:43
Hello @kkharji,
Were you able to fix it?

I was finally able to reproduce your problem.
If the keys of your .env file are:
```.env
CONNECTION_STRING=server=localhost;username=root;password=root
```
And if the `ConfigData` class has the following:
```cs
public class ConfigData
{
     public string ConnectionString { get; set; }
}
```
Then this line will not work as expected:
```cs
builder.Services.Configure<ConfigData>(builder.Configuration);
```
This line not only registers `IOptions<ConfigData>` as a singleton, it also binds each property of the `ConfigData` class to environment variables but in this case `ConfigData.ConnectionString` will not match any keys.

This means that the properties of the `ConfigData` class must match with the keys of the `.env` file (they must have the same name).
That's why you get a null when accessing the `ConfigData.ConnectionString` property, because the binding failed.
What I do dislike is that the `Configure` method did not generate any exception.

The solution is to change the naming convention you use in your .env file, for example:
```.env
ConnectionString=server=localhost;username=root;password=root
```

This problem does not occur with the `EnvBinder` class, because it can bind properties of `ConfigData` to keys using the **UpperCaseSnakeCase** convention.

**Comment by MrDave1999** [comment] 2023-08-29 01:21
I close this issue. I assume you solved the problem.

**Closed by MrDave1999** 2023-08-29 01:21 UTC
